### ISSUE TITLE
Missing compression methods that seemed to work previously

### ISSUE THREAD

**Issue by tillea** [andrix/python-snappy#126]
Hi,
I intended to use [snapista](https://github.com/snap-contrib/snapista) which is using snappy:

    $ grep -R 'from snappy'
    src/snapista/graph.py:from snappy import GPF
    src/snapista/operatorparams.py:from snappy import GPF
    src/snapista/operator.py:from snappy import GPF, jpy

but unfortunately neither GPF nor jpy are working:

    $ python3
    Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from snappy import GPF
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'GPF' from 'snappy' (/usr/lib/python3/dist-packages/snappy/__init__.py)
    >>> from snappy import jpy
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'jpy' from 'snappy' (/usr/lib/python3/dist-packages/snappy/__init__.py)

I've found [some website](https://forum.step.esa.int/t/slower-snappy-processing/6354/5) mentioning even more compression methods (`ProductIO` and `HashMap`) which also do not work in version 0.6.1 which I tried (I also tried version 0.5.3 with same result).  Am I missing something in my setup or is the code using snappy in this way outdated?

Kind regards, Andreas.
